### ISSUE TITLE
Maven registration missing?

### ISSUE THREAD

**Issue by jek** [datapublica/hibernate-pg-json#5]
I can't get maven to find this package- is it in a repository other than central?

**Comment by WydD** [comment]
Sorry just saw the issue now, didnt receive the notification somehow.

Nope we didnt push it to maven central. But it is available using 
```
<repository>
    <id>datapublica-oss</id>
    <name>Data-Publica OpenSource repository</name>
    <url>http://nexus.data-publica.com/content/repositories/public/</url>
</repository>
```
